default: &default
  pool: 5
  adapter: mysql2
  encoding: utf8
  host: localhost
  username: root
  password: leYeThAn


development:
  <<: *default
  database: Theatre_development

test:
  <<: *default
  database: Theatre_tes

production:
  adapter: mysql2
  pool: 5
  encoding: utf8
  url: <%= ENV['DATABASE_URL'] %>
