default: &default
  adapter: sqlite3
  pool: 5

#
# Dev ENV
#
development:
  <<: *default
  database: ../../Theatre_Run/db.sqlite3

test:
  <<: *default
  database: ../../Theatre_Run/db_test.sqlite3

#
# Prod ENV
#
production:
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
