# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b80a01deba1ff3ce675fe5e5f17ad25c847447be9f814e7b004bba30f140c7172d1793b662887d51b1dd0d1de9136b66f5288261004b5a7a51e335eb346355ff

test:
  secret_key_base: c859564fc58410fb7823dfece61dd71f33db12808c9e6e6df92be8d3d6bcf874e67e73adfcd61c7e03319884c2e9c898dc29c54c69e6407b06b464edf68be530

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
